### ISSUE TITLE
Passer en mono-domaine.

### ISSUE THREAD

**Issue by cdaviau** [GIP-RECIA/moodle#19]
Probablement avec un domaine type e-education.recia.fr/moodle ? ou moodle.e-education.recia.fr ?....

**Comment by lvillanne-recia** [comment]
Le plus simple serait d'avoir un domaine comme **moodle.e-education.recia.fr** qui ne nécessiterais pas d'avoir un **/moodle** à la fin.

**Comment by lvillanne-recia** [comment]
Il faudra que je prévois de modifier tout un tas de données en base, probablement par des requêtes sql, pour modifier tous les liens des cours qui pointent vers les différents domaines actuels pour les convertir vers le futur nouveau domaine.

**Comment by jgribonvald** [comment]
L'avantage du domaine `moodle.e-education.recia.fr` est qu'on ne l'utilisera que pour une seule appli, et donc on peut se permettre plus facilement de passer à des certificats let's encrypt gratuit et automatiquement màj. Mais à voir avec Aquaray avant. Mais ça multiplie le nb de domaines à gérer...

**Comment by lvillanne-recia** [comment]
La migration a été réalisé vers https://e-education.recia.fr/moodle/
